command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.58.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true